#!/usr/bin/env python3
"""Regenerate the TRAIN_DIFF_ENTRIES tuple in scripts/weather.py.

Reads assets/train_stop.png, renders the LANDSCAPE_SPANS in weather.py to a
flat RGB buffer, and writes a fresh literal between the BEGIN/END markers in
weather.py. Dev-time only: PIL is required here but NOT at matrix runtime.

Run from the repo root:

    python3 scripts/regen_train_diff.py
"""

from __future__ import annotations

import importlib.util
import re
import sys
import types
from pathlib import Path

from PIL import Image


REPO_ROOT = Path(__file__).resolve().parent.parent
WEATHER_PATH = REPO_ROOT / "scripts" / "weather.py"
STOP_PNG_PATH = REPO_ROOT / "assets" / "train_stop.png"
BEGIN_MARKER = "    # >>> BEGIN TRAIN_DIFF_ENTRIES (regenerated by regen_train_diff.py)"
END_MARKER = "    # <<< END TRAIN_DIFF_ENTRIES"


def _load_weather_module():
    """Import scripts/weather.py with a stubbed rgbmatrix so PALETTE,
    LANDSCAPE_SPANS, W/H, and the bbox constants are available."""
    fake = types.ModuleType("rgbmatrix")
    fake.graphics = types.ModuleType("graphics")

    class _Font:
        def LoadFont(self, *_a, **_k):
            pass

    fake.graphics.Font = _Font
    fake.graphics.Color = lambda *a: a
    fake.graphics.DrawText = lambda *a, **k: 0
    sys.modules["rgbmatrix"] = fake
    sys.modules["rgbmatrix.graphics"] = fake.graphics

    spec = importlib.util.spec_from_file_location("weather", WEATHER_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _render_landscape(weather):
    buf = [[(0, 0, 0)] * weather.W for _ in range(weather.H)]
    for y, row in enumerate(weather.LANDSCAPE_SPANS):
        for x0, length, palette_index in row:
            col = weather.PALETTE[palette_index]
            for x in range(x0, x0 + length):
                if 0 <= x < weather.W and 0 <= y < weather.H:
                    buf[y][x] = col
    return buf


def _diff_entries(weather, landscape, stop_pixels):
    entries = []
    for y in range(weather.TRAIN_BBOX_Y0, weather.TRAIN_BBOX_Y1 + 1):
        for x in range(weather.TRAIN_BBOX_X0, weather.TRAIN_BBOX_X1 + 1):
            train_col = landscape[y][x]
            stop_col = stop_pixels[x, y]
            if train_col != stop_col:
                entries.append((x - weather.TRAIN_HOME_X, y, train_col, stop_col))
    return entries


def _format_block(entries):
    lines = [BEGIN_MARKER]
    last_y = None
    for dx, y, train_col, stop_col in entries:
        if y != last_y:
            lines.append(f"    # y = {y}")
            last_y = y
        lines.append(f"    ({dx}, {y}, {train_col}, {stop_col}),")
    lines.append(END_MARKER)
    return "\n".join(lines)


def main() -> int:
    weather = _load_weather_module()
    landscape = _render_landscape(weather)
    stop = Image.open(STOP_PNG_PATH).convert("RGB")
    if stop.size != (weather.W, weather.H):
        raise SystemExit(
            f"{STOP_PNG_PATH} is {stop.size}, expected ({weather.W}, {weather.H})"
        )

    entries = _diff_entries(weather, landscape, stop.load())
    block = _format_block(entries)

    src = WEATHER_PATH.read_text()
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    if not pattern.search(src):
        raise SystemExit(
            "Could not find BEGIN/END TRAIN_DIFF_ENTRIES markers in weather.py"
        )
    new_src = pattern.sub(block, src)
    WEATHER_PATH.write_text(new_src)
    print(f"Updated {WEATHER_PATH} with {len(entries)} entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
