#!/usr/bin/env python3
"""Regenerate the TRAIN_DIFF_ENTRIES tuple in scripts/weather_scene.py.

Reads assets/train_stop.png, renders the LANDSCAPE_SPANS in weather_scene.py to a
flat RGB buffer, and writes a fresh literal between the BEGIN/END markers in
weather_scene.py. Dev-time only: PIL is required here but NOT at matrix runtime.

Run from the repo root:

    python3 scripts/regen_train_diff.py
"""

from __future__ import annotations

import importlib.util
import re
import sys
import types
from pathlib import Path

from PIL import Image


REPO_ROOT = Path(__file__).resolve().parent.parent
WEATHER_SCENE_PATH = REPO_ROOT / "scripts" / "weather_scene.py"
STOP_PNG_PATH = REPO_ROOT / "assets" / "train_stop.png"
BEGIN_MARKER = "    # >>> BEGIN TRAIN_DIFF_ENTRIES (regenerated by regen_train_diff.py)"
END_MARKER = "    # <<< END TRAIN_DIFF_ENTRIES"
STOP_BEGIN_MARKER = "    # >>> BEGIN TRAIN_STOP_SPANS (regenerated by regen_train_diff.py)"
STOP_END_MARKER = "    # <<< END TRAIN_STOP_SPANS"


def _load_weather_scene_module():
    """Import scripts/weather_scene.py with a stubbed rgbmatrix so PALETTE,
    LANDSCAPE_SPANS, W/H, and the bbox constants are available."""
    fake = types.ModuleType("rgbmatrix")
    fake.graphics = types.ModuleType("graphics")

    class _Font:
        def LoadFont(self, *_a, **_k):
            pass

    fake.graphics.Font = _Font
    fake.graphics.Color = lambda *a: a
    fake.graphics.DrawText = lambda *a, **k: 0
    sys.modules["rgbmatrix"] = fake
    sys.modules["rgbmatrix.graphics"] = fake.graphics

    spec = importlib.util.spec_from_file_location("weather_scene", WEATHER_SCENE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _render_landscape(weather_scene):
    buf = [[(0, 0, 0)] * weather_scene.W for _ in range(weather_scene.H)]
    for y, row in enumerate(weather_scene.LANDSCAPE_SPANS):
        for x0, length, palette_index in row:
            col = weather_scene.PALETTE[palette_index]
            for x in range(x0, x0 + length):
                if 0 <= x < weather_scene.W and 0 <= y < weather_scene.H:
                    buf[y][x] = col
    return buf


def _diff_entries(weather_scene, landscape, stop_pixels):
    """Build diff entries for the mirrored, double-cab train.

    The source landscape has a single-cab train baked at cols
    TRAIN_SOURCE_ORIGIN..TRAIN_SOURCE_ORIGIN+20. The "real" train sprite is
    defined by the set of positions where the source landscape differs from
    train_stop.png. The blue glazing is intentionally forced into the sprite
    mask even when it matches the stop/background color so the windows move
    with the train.

    We first collect that authoritative train mask from the source. Then for
    each source pixel we emit a new entry at sprite_dx = src_dx, and (if
    src_dx is in front of the mirror axis) also at sprite_dx = 2*axis - src_dx.
    The new stop_color is taken from train_stop.png at the *new* parked column.
    """
    axis = weather_scene.TRAIN_MIRROR_AXIS
    src = weather_scene.TRAIN_SOURCE_ORIGIN
    home = weather_scene.TRAIN_HOME_X

    seen = set()
    entries = []

    def emit(dx, y, train_col, force=False):
        if dx < 0 or dx >= weather_scene.TRAIN_WIDTH:
            return
        if (dx, y) in seen:
            return
        stop_col = stop_pixels[home + dx, y]
        if train_col == stop_col and not force:
            return
        seen.add((dx, y))
        entries.append((dx, y, train_col, stop_col))

    source_width = weather_scene.W - src  # source train baked from `src` to right edge
    sprite_y0 = getattr(weather_scene, "TRAIN_SPRITE_Y0", weather_scene.TRAIN_BBOX_Y0)
    glazing_regions = getattr(weather_scene, "ION_TRAIN_GLAZING_REGIONS", ())
    excluded = set(getattr(weather_scene, "TRAIN_SPRITE_EXCLUDE_PIXELS", ()))
    for y in range(sprite_y0, weather_scene.TRAIN_BBOX_Y1 + 1):
        for src_dx in range(source_width):
            train_col = landscape[y][src + src_dx]
            stop_col_src = stop_pixels[src + src_dx, y]
            dx = src_dx
            if (dx, y) in excluded:
                continue
            force = weather_scene.in_any_region(home + dx, y, glazing_regions)
            if train_col == stop_col_src and not force:
                continue  # not part of the train sprite
            emit(dx, y, train_col, force)
            if src_dx < axis:
                mirror_dx = 2 * axis - src_dx
                if (mirror_dx, y) in excluded:
                    continue
                mirror_force = weather_scene.in_any_region(home + mirror_dx, y, glazing_regions)
                emit(mirror_dx, y, train_col, mirror_force)

    entries.sort(key=lambda e: (e[1], e[0]))
    return entries


def _format_block(entries):
    lines = [BEGIN_MARKER]
    last_y = None
    for dx, y, train_col, stop_col in entries:
        if y != last_y:
            lines.append(f"    # y = {y}")
            last_y = y
        lines.append(f"    ({dx}, {y}, {train_col}, {stop_col}),")
    lines.append(END_MARKER)
    return "\n".join(lines)


def _stop_spans(weather_scene, stop_pixels):
    rows = []
    for y in range(weather_scene.TRAIN_BBOX_Y0, weather_scene.TRAIN_BBOX_Y1 + 1):
        spans = []
        run_start = 0
        prev = stop_pixels[weather_scene.TRAIN_HOME_X, y]
        for dx in range(1, weather_scene.TRAIN_WIDTH):
            col = stop_pixels[weather_scene.TRAIN_HOME_X + dx, y]
            if col == prev:
                continue
            spans.append((run_start, dx - run_start, prev))
            run_start = dx
            prev = col
        spans.append((run_start, weather_scene.TRAIN_WIDTH - run_start, prev))
        rows.append((y, spans))
    return rows


def _format_stop_block(rows):
    lines = [STOP_BEGIN_MARKER]
    for y, spans in rows:
        lines.append(f"    # y = {y}")
        lines.append(f"    {tuple(spans)!r},")
    lines.append(STOP_END_MARKER)
    return "\n".join(lines)


def main() -> int:
    weather_scene = _load_weather_scene_module()
    landscape = _render_landscape(weather_scene)
    stop = Image.open(STOP_PNG_PATH).convert("RGB")
    if stop.size != (weather_scene.W, weather_scene.H):
        raise SystemExit(
            f"{STOP_PNG_PATH} is {stop.size}, expected ({weather_scene.W}, {weather_scene.H})"
        )

    entries = _diff_entries(weather_scene, landscape, stop.load())
    block = _format_block(entries)
    stop_block = _format_stop_block(_stop_spans(weather_scene, stop.load()))

    src = WEATHER_SCENE_PATH.read_text()
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    if not pattern.search(src):
        raise SystemExit(
            "Could not find BEGIN/END TRAIN_DIFF_ENTRIES markers in weather_scene.py"
        )
    new_src = pattern.sub(block, src)
    stop_pattern = re.compile(
        re.escape(STOP_BEGIN_MARKER) + r".*?" + re.escape(STOP_END_MARKER), re.DOTALL
    )
    if not stop_pattern.search(new_src):
        raise SystemExit(
            "Could not find BEGIN/END TRAIN_STOP_SPANS markers in weather_scene.py"
        )
    new_src = stop_pattern.sub(stop_block, new_src)
    WEATHER_SCENE_PATH.write_text(new_src)
    print(f"Updated {WEATHER_SCENE_PATH} with {len(entries)} train entries and stop spans.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
